## We use this for tests, do not deploy using this docker-compose!!!

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:2025.12.2"
    volumes:
      - ./.ha-test-config:/config
      - ./custom_components/hydroqc:/config/custom_components/hydroqc:ro
      - ./blueprints:/config/blueprints/automation/hydroqc:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8123:8123"
    privileged: true