blank_issues_enabled: false
contact_links:
  - name: ğŸ“š Documentation
    url: https://github.com/hydroqc/hydroqc-ha/blob/main/README.md
    about: Lire la documentation de l'intÃ©gration
  - name: ğŸ’¬ Discussions
    url: https://github.com/hydroqc/hydroqc-ha/discussions
    about: Poser des questions et discuter avec la communautÃ©
  - name: ğŸŒ Guide de tarification dynamique Hydro-QuÃ©bec
    url: https://hydroqc.ca/fr/docs/tarification-dynamique/
    about: En savoir plus sur les tarifs dynamiques d'Hydro-QuÃ©bec
